### PR TITLE
doc.go, examples_test.go: improve DevExp with doc and examples

### PR DESCRIPTION
**Pull request by odeke-em**
Updates #32 

* Added an overview doc.go file
* Added end to end examples that are runnable and copy+pastable
for RegisterInterface, WriteBinary, ReadBinary

### CODE REVIEW

**Comment by odeke-em** [comment]
Exhibit
---
screen shot 2017-09-19 at 6 05 39 pm

screen shot 2017-09-19 at 6 05 51 pm

**Review by zramsay — APPROVED** [review]

**Review by melekes — APPROVED** [review]

**Review by ethanfrey — COMMENTED** [review]
This is a very nice write up, but I think the API it documents needs to rewritten (see #23)

I would at least use `BinaryBytes` adn `ReadBinaryBytes` as the typical entry points instead of `WriteBinary` and `ReadBinary`, as they are simpler to use.

But the reason you cannot find those among the 67 other functions is why I think the whole API needs a cleanup.

In short, I love the docs, I don't like the API it documents.

**Comment by ebuchman** [comment]
ill merge this but we should have the API redesign discussion.

**Pull request merged**
