### PR TITLE
WIP: Sdk2: marshal+unmarshal JSON with disambiguation implemented

### PR DESCRIPTION
**Pull request by odeke-em**
Following the structure of *Codec.MarshalBinary as requested by @jaekwon, this code is a WIP to implement JSON Marshaling.

It is the alternate to https://github.com/tendermint/go-wire/pull/80 which doesn't follow the requested structuring of code.

Please leave both PRs open while this one is a WIP to compare and contrast features.

### CODE REVIEW

**Comment by odeke-em** [comment]
Alright @jaekwon, please see the first iteration of the JSON codec, thank you for the feedback offline and for the review!

**Comment by rigelrozanski** [comment]
Dope this works for non-embedded serialization, problems introduced still if embed in higher level structs: https://github.com/rigelrozanski/rational-test

**Comment by odeke-em** [comment]
Thank you for reporting this @rigelrozanski, let me take a look at that.

**Comment by odeke-em** [comment]
@rigelrozanski we have tests for even embedded structs as per 
https://github.com/tendermint/go-wire/pull/83/files#diff-28aea91bac84cd18870296d459932866R42

and I've also pulled in your rational_test code and all the tests pass
screen shot 2018-01-23 at 5 30 56 pm

with some modifications that I'll send as a PR to the mothership :)

**Comment by rigelrozanski** [comment]
@odeke-em  Coming along... K so I your tests work within the previous context with the updated diff code you provided... There is however new issues provided when registering as a part of an interface... you can see my last two commits in https://github.com/rigelrozanski/rational-test to get a sense of the issue (last one is failing under embedded type tests, 2nd last one is passing with your changes)

Error output here:
https://github.com/rigelrozanski/rational-test/issues/2

**Pull request merged**
