### PR TITLE
fix and speed up trim null bytes code

### LINKED ISSUE #88: sdk2: fix invalid and expensive byte trim code
I was just reviewing the code to see why our tests take 67seconds to run and noticed that
throughout in the code we have patterns of code such as
https://github.com/tendermint/go-wire/blob/c7801c1586f51bb28028cd420c599516d7ac9c36/reflect.go#L809-L811

and
https://github.com/tendermint/go-wire/blob/c7801c1586f51bb28028cd420c599516d7ac9c36/reflect.go#L814-L816

the above pattern is both invalid and slow, it'll runtime panic if the entire byte slice has 0x00 but also it resizes the slice every single time.

We can generate faster code and correct code by doing
```go
func trimNullBytesPrefix(bz []byte) {
        i := 0
        for i < len(bz) {
                if bz[i] != 0x00 {
                        break
                }
                i++
        }
        if i >= 1 {
                bz = bz[i:]
        }
}
```

### PR DESCRIPTION
**Pull request by odeke-em**
The previous code will runtime panic if we
happen to have a byte slice with only 0x00.
And it also resizes the byte slice in every
step hence quite slow.

Speed it up and make it correct by extracting
it out to a helper function. It shaves off 2 seconds
from our testing code.

Fixes #88

### CODE REVIEW

**Comment by melekes** [comment]
Needs rebase

**Comment by veorq** [comment]
It's a thing I report in my audit, it's actually more general than just the all-zero string. According to my analysis there's about 2^54 strings that'll trigger a panic, but that's still negligible even if you process billions of names.

**Comment by jaekwon** [comment]
The solution is incorrect and rebase is difficult right now so lets just redo this if you feel that it's a problem.

**Comment by odeke-em** [comment]
Forgot to return the trimmed bytes. @jaekwon how did this PR with 1 file turn into 73 files changed?

**Pull request closed without merging**
